package far2go

const (
	FOREGROUND_BLUE      = 0x0001 // text color contains blue.
	FOREGROUND_GREEN     = 0x0002 // text color contains green.
	FOREGROUND_RED       = 0x0004 // text color contains red.
	FOREGROUND_INTENSITY = 0x0008 // text color is intensified.
	BACKGROUND_BLUE      = 0x0010 // background color contains blue.
	BACKGROUND_GREEN     = 0x0020 // background color contains green.
	BACKGROUND_RED       = 0x0040 // background color contains red.
	BACKGROUND_INTENSITY = 0x0080 // background color is intensified.
	F_BLACK              = 0
	F_BLUE               = FOREGROUND_BLUE
	F_GREEN              = FOREGROUND_GREEN
	F_CYAN               = FOREGROUND_BLUE | FOREGROUND_GREEN
	F_RED                = FOREGROUND_RED
	F_MAGENTA            = FOREGROUND_BLUE | FOREGROUND_RED
	F_BROWN              = FOREGROUND_GREEN | FOREGROUND_RED
	F_LIGHTGRAY          = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED
	F_DARKGRAY           = FOREGROUND_INTENSITY
	F_LIGHTBLUE          = FOREGROUND_BLUE | FOREGROUND_INTENSITY
	F_LIGHTGREEN         = FOREGROUND_GREEN | FOREGROUND_INTENSITY
	F_LIGHTCYAN          = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_INTENSITY
	F_LIGHTRED           = FOREGROUND_RED | FOREGROUND_INTENSITY
	F_LIGHTMAGENTA       = FOREGROUND_BLUE | FOREGROUND_RED | FOREGROUND_INTENSITY
	F_YELLOW             = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY
	F_WHITE              = FOREGROUND_BLUE | FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY
	B_BLACK              = 0
	B_BLUE               = BACKGROUND_BLUE
	B_GREEN              = BACKGROUND_GREEN
	B_CYAN               = BACKGROUND_BLUE | BACKGROUND_GREEN
	B_RED                = BACKGROUND_RED
	B_MAGENTA            = BACKGROUND_BLUE | BACKGROUND_RED
	B_BROWN              = BACKGROUND_GREEN | BACKGROUND_RED
	B_LIGHTGRAY          = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED
	B_DARKGRAY           = BACKGROUND_INTENSITY
	B_LIGHTBLUE          = BACKGROUND_BLUE | BACKGROUND_INTENSITY
	B_LIGHTGREEN         = BACKGROUND_GREEN | BACKGROUND_INTENSITY
	B_LIGHTCYAN          = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_INTENSITY
	B_LIGHTRED           = BACKGROUND_RED | BACKGROUND_INTENSITY
	B_LIGHTMAGENTA       = BACKGROUND_BLUE | BACKGROUND_RED | BACKGROUND_INTENSITY
	B_YELLOW             = BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY
	B_WHITE              = BACKGROUND_BLUE | BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY
	F_MASK               = F_WHITE
	B_MASK               = B_WHITE
)

type PaletteColor uint

const (
	COL_FIRSTPALETTECOLOR     PaletteColor = iota
	COL_MENUTEXT
	COL_MENUSELECTEDTEXT
	COL_MENUHIGHLIGHT
	COL_MENUSELECTEDHIGHLIGHT
	COL_MENUBOX
	COL_MENUTITLE

	COL_HMENUTEXT
	COL_HMENUSELECTEDTEXT
	COL_HMENUHIGHLIGHT
	COL_HMENUSELECTEDHIGHLIGHT

	COL_PANELTEXT
	COL_PANELSELECTEDTEXT
	COL_PANELHIGHLIGHTTEXT
	COL_PANELINFOTEXT
	COL_PANELCURSOR
	COL_PANELSELECTEDCURSOR
	COL_PANELTITLE
	COL_PANELSELECTEDTITLE
	COL_PANELCOLUMNTITLE
	COL_PANELTOTALINFO
	COL_PANELSELECTEDINFO

	COL_DIALOGTEXT
	COL_DIALOGHIGHLIGHTTEXT
	COL_DIALOGBOX
	COL_DIALOGBOXTITLE
	COL_DIALOGHIGHLIGHTBOXTITLE
	COL_DIALOGEDIT
	COL_DIALOGBUTTON
	COL_DIALOGSELECTEDBUTTON
	COL_DIALOGHIGHLIGHTBUTTON
	COL_DIALOGHIGHLIGHTSELECTEDBUTTON

	COL_DIALOGLISTTEXT
	COL_DIALOGLISTSELECTEDTEXT
	COL_DIALOGLISTHIGHLIGHT
	COL_DIALOGLISTSELECTEDHIGHLIGHT

	COL_WARNDIALOGTEXT
	COL_WARNDIALOGHIGHLIGHTTEXT
	COL_WARNDIALOGBOX
	COL_WARNDIALOGBOXTITLE
	COL_WARNDIALOGHIGHLIGHTBOXTITLE
	COL_WARNDIALOGEDIT
	COL_WARNDIALOGBUTTON
	COL_WARNDIALOGSELECTEDBUTTON
	COL_WARNDIALOGHIGHLIGHTBUTTON
	COL_WARNDIALOGHIGHLIGHTSELECTEDBUTTON

	COL_KEYBARNUM
	COL_KEYBARTEXT
	COL_KEYBARBACKGROUND

	COL_COMMANDLINE

	COL_CLOCK

	COL_VIEWERTEXT
	COL_VIEWERSELECTEDTEXT
	COL_VIEWERSTATUS

	COL_EDITORTEXT
	COL_EDITORSELECTEDTEXT
	COL_EDITORSTATUS

	COL_HELPTEXT
	COL_HELPHIGHLIGHTTEXT
	COL_HELPTOPIC
	COL_HELPSELECTEDTOPIC
	COL_HELPBOX
	COL_HELPBOXTITLE

	COL_PANELDRAGTEXT
	COL_DIALOGEDITUNCHANGED
	COL_PANELSCROLLBAR
	COL_HELPSCROLLBAR
	COL_PANELBOX
	COL_PANELSCREENSNUMBER
	COL_DIALOGEDITSELECTED
	COL_COMMANDLINESELECTED
	COL_VIEWERARROWS

	COL_PRIVATEPOSITION_FOR_DIF165ABOVE
	COL_RESERVED0

	COL_DIALOGLISTSCROLLBAR
	COL_MENUSCROLLBAR
	COL_VIEWERSCROLLBAR
	COL_COMMANDLINEPREFIX
	COL_DIALOGDISABLED
	COL_DIALOGEDITDISABLED
	COL_DIALOGLISTDISABLED
	COL_WARNDIALOGDISABLED
	COL_WARNDIALOGEDITDISABLED
	COL_WARNDIALOGLISTDISABLED

	COL_MENUDISABLEDTEXT

	COL_EDITORCLOCK
	COL_VIEWERCLOCK

	COL_DIALOGLISTTITLE
	COL_DIALOGLISTBOX

	COL_WARNDIALOGEDITSELECTED
	COL_WARNDIALOGEDITUNCHANGED

	COL_DIALOGCOMBOTEXT
	COL_DIALOGCOMBOSELECTEDTEXT
	COL_DIALOGCOMBOHIGHLIGHT
	COL_DIALOGCOMBOSELECTEDHIGHLIGHT
	COL_DIALOGCOMBOBOX
	COL_DIALOGCOMBOTITLE
	COL_DIALOGCOMBODISABLED
	COL_DIALOGCOMBOSCROLLBAR

	COL_WARNDIALOGLISTTEXT
	COL_WARNDIALOGLISTSELECTEDTEXT
	COL_WARNDIALOGLISTHIGHLIGHT
	COL_WARNDIALOGLISTSELECTEDHIGHLIGHT
	COL_WARNDIALOGLISTBOX
	COL_WARNDIALOGLISTTITLE
	COL_WARNDIALOGLISTSCROLLBAR

	COL_WARNDIALOGCOMBOTEXT
	COL_WARNDIALOGCOMBOSELECTEDTEXT
	COL_WARNDIALOGCOMBOHIGHLIGHT
	COL_WARNDIALOGCOMBOSELECTEDHIGHLIGHT
	COL_WARNDIALOGCOMBOBOX
	COL_WARNDIALOGCOMBOTITLE
	COL_WARNDIALOGCOMBODISABLED
	COL_WARNDIALOGCOMBOSCROLLBAR

	COL_DIALOGLISTARROWS
	COL_DIALOGLISTARROWSDISABLED
	COL_DIALOGLISTARROWSSELECTED
	COL_DIALOGCOMBOARROWS
	COL_DIALOGCOMBOARROWSDISABLED
	COL_DIALOGCOMBOARROWSSELECTED
	COL_WARNDIALOGLISTARROWS
	COL_WARNDIALOGLISTARROWSDISABLED
	COL_WARNDIALOGLISTARROWSSELECTED
	COL_WARNDIALOGCOMBOARROWS
	COL_WARNDIALOGCOMBOARROWSDISABLED
	COL_WARNDIALOGCOMBOARROWSSELECTED
	COL_MENUARROWS
	COL_MENUARROWSDISABLED
	COL_MENUARROWSSELECTED
	COL_COMMANDLINEUSERSCREEN
	COL_EDITORSCROLLBAR

	COL_MENUGRAYTEXT
	COL_MENUSELECTEDGRAYTEXT
	COL_DIALOGCOMBOGRAY
	COL_DIALOGCOMBOSELECTEDGRAYTEXT
	COL_DIALOGLISTGRAY
	COL_DIALOGLISTSELECTEDGRAYTEXT
	COL_WARNDIALOGCOMBOGRAY
	COL_WARNDIALOGCOMBOSELECTEDGRAYTEXT
	COL_WARNDIALOGLISTGRAY
	COL_WARNDIALOGLISTSELECTEDGRAYTEXT

	COL_DIALOGDEFAULTBUTTON
	COL_DIALOGSELECTEDDEFAULTBUTTON
	COL_DIALOGHIGHLIGHTDEFAULTBUTTON
	COL_DIALOGHIGHLIGHTSELECTEDDEFAULTBUTTON
	COL_WARNDIALOGDEFAULTBUTTON
	COL_WARNDIALOGSELECTEDDEFAULTBUTTON
	COL_WARNDIALOGHIGHLIGHTDEFAULTBUTTON
	COL_WARNDIALOGHIGHLIGHTSELECTEDDEFAULTBUTTON

	COL_LASTPALETTECOLOR
)
