package far2go

type KeyCode uint

const (
	/*
	* Virtual Keys  Standard Set
	*/
	VK_LBUTTON KeyCode = 0x01
	VK_RBUTTON KeyCode = 0x02
	VK_CANCEL  KeyCode = 0x03
	VK_MBUTTON KeyCode = 0x04 /* NOT contiguous with L & RBUTTON */

	VK_XBUTTON1 KeyCode = 0x05 /* NOT contiguous with L & RBUTTON */
	VK_XBUTTON2 KeyCode = 0x06 /* NOT contiguous with L & RBUTTON */

	/*
	 * 0x07 : unassigned
	 */

	VK_BACK KeyCode = 0x08
	VK_TAB  KeyCode = 0x09

	/*
	 * 0x0A - 0x0B : reserved
	 */

	VK_CLEAR  KeyCode = 0x0C
	VK_RETURN KeyCode = 0x0D

	VK_SHIFT   KeyCode = 0x10
	VK_CONTROL KeyCode = 0x11
	VK_MENU    KeyCode = 0x12
	VK_PAUSE   KeyCode = 0x13
	VK_CAPITAL KeyCode = 0x14

	VK_KANA    KeyCode = 0x15
	VK_HANGEUL KeyCode = 0x15 /* old name - should be here for compatibility */
	VK_HANGUL  KeyCode = 0x15
	VK_JUNJA   KeyCode = 0x17
	VK_FINAL   KeyCode = 0x18
	VK_HANJA   KeyCode = 0x19
	VK_KANJI   KeyCode = 0x19

	VK_ESCAPE KeyCode = 0x1B

	VK_CONVERT    KeyCode = 0x1C
	VK_NONCONVERT KeyCode = 0x1D
	VK_ACCEPT     KeyCode = 0x1E
	VK_MODECHANGE KeyCode = 0x1F

	VK_SPACE    KeyCode = 0x20
	VK_PRIOR    KeyCode = 0x21
	VK_NEXT     KeyCode = 0x22
	VK_END      KeyCode = 0x23
	VK_HOME     KeyCode = 0x24
	VK_LEFT     KeyCode = 0x25
	VK_UP       KeyCode = 0x26
	VK_RIGHT    KeyCode = 0x27
	VK_DOWN     KeyCode = 0x28
	VK_SELECT   KeyCode = 0x29
	VK_PRINT    KeyCode = 0x2A
	VK_EXECUTE  KeyCode = 0x2B
	VK_SNAPSHOT KeyCode = 0x2C
	VK_INSERT   KeyCode = 0x2D
	VK_DELETE   KeyCode = 0x2E
	VK_HELP     KeyCode = 0x2F

	/*
	 * VK_0 - VK_9 are the same as ASCII '0' - '9' (0x30 - 0x39)
	 * 0x40 : unassigned
	 * VK_A - VK_Z are the same as ASCII 'A' - 'Z' (0x41 - 0x5A)
	 */

	VK_LWIN KeyCode = 0x5B
	VK_RWIN KeyCode = 0x5C
	VK_APPS KeyCode = 0x5D

	/*
	 * 0x5E : reserved
	 */

	VK_SLEEP KeyCode = 0x5F

	VK_NUMPAD0   KeyCode = 0x60
	VK_NUMPAD1   KeyCode = 0x61
	VK_NUMPAD2   KeyCode = 0x62
	VK_NUMPAD3   KeyCode = 0x63
	VK_NUMPAD4   KeyCode = 0x64
	VK_NUMPAD5   KeyCode = 0x65
	VK_NUMPAD6   KeyCode = 0x66
	VK_NUMPAD7   KeyCode = 0x67
	VK_NUMPAD8   KeyCode = 0x68
	VK_NUMPAD9   KeyCode = 0x69
	VK_MULTIPLY  KeyCode = 0x6A
	VK_ADD       KeyCode = 0x6B
	VK_SEPARATOR KeyCode = 0x6C
	VK_SUBTRACT  KeyCode = 0x6D
	VK_DECIMAL   KeyCode = 0x6E
	VK_DIVIDE    KeyCode = 0x6F
	VK_F1        KeyCode = 0x70
	VK_F2        KeyCode = 0x71
	VK_F3        KeyCode = 0x72
	VK_F4        KeyCode = 0x73
	VK_F5        KeyCode = 0x74
	VK_F6        KeyCode = 0x75
	VK_F7        KeyCode = 0x76
	VK_F8        KeyCode = 0x77
	VK_F9        KeyCode = 0x78
	VK_F10       KeyCode = 0x79
	VK_F11       KeyCode = 0x7A
	VK_F12       KeyCode = 0x7B
	VK_F13       KeyCode = 0x7C
	VK_F14       KeyCode = 0x7D
	VK_F15       KeyCode = 0x7E
	VK_F16       KeyCode = 0x7F
	VK_F17       KeyCode = 0x80
	VK_F18       KeyCode = 0x81
	VK_F19       KeyCode = 0x82
	VK_F20       KeyCode = 0x83
	VK_F21       KeyCode = 0x84
	VK_F22       KeyCode = 0x85
	VK_F23       KeyCode = 0x86
	VK_F24       KeyCode = 0x87

	/*
	 * 0x88 - 0x8F : unassigned
	 */

	VK_NUMLOCK KeyCode = 0x90
	VK_SCROLL  KeyCode = 0x91

	/*
	 * VK_L* & VK_R* - left and right Alt  Ctrl and Shift virtual keys.
	 * Used only as parameters to GetAsyncKeyState() and GetKeyState().
	 * No other API or message will distinguish left and right keys in this way.
	 */
	VK_LSHIFT   KeyCode = 0xA0
	VK_RSHIFT   KeyCode = 0xA1
	VK_LCONTROL KeyCode = 0xA2
	VK_RCONTROL KeyCode = 0xA3
	VK_LMENU    KeyCode = 0xA4
	VK_RMENU    KeyCode = 0xA5

	VK_BROWSER_BACK      KeyCode = 0xA6
	VK_BROWSER_FORWARD   KeyCode = 0xA7
	VK_BROWSER_REFRESH   KeyCode = 0xA8
	VK_BROWSER_STOP      KeyCode = 0xA9
	VK_BROWSER_SEARCH    KeyCode = 0xAA
	VK_BROWSER_FAVORITES KeyCode = 0xAB
	VK_BROWSER_HOME      KeyCode = 0xAC

	VK_VOLUME_MUTE         KeyCode = 0xAD
	VK_VOLUME_DOWN         KeyCode = 0xAE
	VK_VOLUME_UP           KeyCode = 0xAF
	VK_MEDIA_NEXT_TRACK    KeyCode = 0xB0
	VK_MEDIA_PREV_TRACK    KeyCode = 0xB1
	VK_MEDIA_STOP          KeyCode = 0xB2
	VK_MEDIA_PLAY_PAUSE    KeyCode = 0xB3
	VK_LAUNCH_MAIL         KeyCode = 0xB4
	VK_LAUNCH_MEDIA_SELECT KeyCode = 0xB5
	VK_LAUNCH_APP1         KeyCode = 0xB6
	VK_LAUNCH_APP2         KeyCode = 0xB7

	EXTENDED_KEY_BASE   KeyCode = 0x00010000
	INTERNAL_KEY_BASE   KeyCode = 0x00020000
	INTERNAL_KEY_BASE_2 KeyCode = 0x00030000
	INTERNAL_MACRO_BASE KeyCode = 0x00080000
)

const (
	KEY_CTRLMASK KeyCode = 0xFFF00000

	KEY_M_OEM  KeyCode = 0x00100000
	KEY_M_SPEC KeyCode = 0x00200000

	KEY_CTRL  KeyCode = 0x01000000
	KEY_ALT   KeyCode = 0x02000000
	KEY_SHIFT KeyCode = 0x04000000
	KEY_RCTRL KeyCode = 0x10000000
	KEY_RALT  KeyCode = 0x20000000

	KEY_ALTDIGIT KeyCode = 0x40000000
	KEY_RSHIFT   KeyCode = 0x80000000

	KEY_BRACKET     KeyCode = '['
	KEY_BACKBRACKET KeyCode = ']'
	KEY_COMMA       KeyCode = ' '
	KEY_QUOTE       KeyCode = '"'
	KEY_DOT         KeyCode = '.'
	KEY_SLASH       KeyCode = '/'
	KEY_COLON       KeyCode = ':'
	KEY_SEMICOLON   KeyCode = ';'
	KEY_BACKSLASH   KeyCode = '\\'

	KEY_BS    KeyCode = 0x00000008
	KEY_TAB   KeyCode = 0x00000009
	KEY_ENTER KeyCode = 0x0000000D
	KEY_ESC   KeyCode = 0x0000001B
	KEY_SPACE KeyCode = 0x00000020

	KEY_MASKF KeyCode = 0x0001FFFF

	KEY_FKEY_BEGIN KeyCode = EXTENDED_KEY_BASE

	KEY_BREAK KeyCode = EXTENDED_KEY_BASE + VK_CANCEL

	KEY_PAUSE    KeyCode = EXTENDED_KEY_BASE + VK_PAUSE
	KEY_CAPSLOCK KeyCode = EXTENDED_KEY_BASE + VK_CAPITAL

	KEY_PGUP     KeyCode = EXTENDED_KEY_BASE + VK_PRIOR
	KEY_PGDN     KeyCode = EXTENDED_KEY_BASE + VK_NEXT
	KEY_END      KeyCode = EXTENDED_KEY_BASE + VK_END
	KEY_HOME     KeyCode = EXTENDED_KEY_BASE + VK_HOME
	KEY_LEFT     KeyCode = EXTENDED_KEY_BASE + VK_LEFT
	KEY_UP       KeyCode = EXTENDED_KEY_BASE + VK_UP
	KEY_RIGHT    KeyCode = EXTENDED_KEY_BASE + VK_RIGHT
	KEY_DOWN     KeyCode = EXTENDED_KEY_BASE + VK_DOWN
	KEY_PRNTSCRN KeyCode = EXTENDED_KEY_BASE + VK_SNAPSHOT
	KEY_INS      KeyCode = EXTENDED_KEY_BASE + VK_INSERT
	KEY_DEL      KeyCode = EXTENDED_KEY_BASE + VK_DELETE

	KEY_LWIN    KeyCode = EXTENDED_KEY_BASE + VK_LWIN
	KEY_RWIN    KeyCode = EXTENDED_KEY_BASE + VK_RWIN
	KEY_APPS    KeyCode = EXTENDED_KEY_BASE + VK_APPS
	KEY_STANDBY KeyCode = EXTENDED_KEY_BASE + VK_SLEEP

	KEY_NUMPAD0 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD0
	KEY_NUMPAD1 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD1
	KEY_NUMPAD2 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD2
	KEY_NUMPAD3 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD3
	KEY_NUMPAD4 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD4
	KEY_NUMPAD5 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD5
	KEY_CLEAR   KeyCode = KEY_NUMPAD5
	KEY_NUMPAD6 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD6
	KEY_NUMPAD7 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD7
	KEY_NUMPAD8 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD8
	KEY_NUMPAD9 KeyCode = EXTENDED_KEY_BASE + VK_NUMPAD9

	KEY_MULTIPLY KeyCode = EXTENDED_KEY_BASE + VK_MULTIPLY
	KEY_ADD      KeyCode = EXTENDED_KEY_BASE + VK_ADD
	KEY_SUBTRACT KeyCode = EXTENDED_KEY_BASE + VK_SUBTRACT
	KEY_DECIMAL  KeyCode = EXTENDED_KEY_BASE + VK_DECIMAL
	KEY_DIVIDE   KeyCode = EXTENDED_KEY_BASE + VK_DIVIDE

	KEY_F1  KeyCode = EXTENDED_KEY_BASE + VK_F1
	KEY_F2  KeyCode = EXTENDED_KEY_BASE + VK_F2
	KEY_F3  KeyCode = EXTENDED_KEY_BASE + VK_F3
	KEY_F4  KeyCode = EXTENDED_KEY_BASE + VK_F4
	KEY_F5  KeyCode = EXTENDED_KEY_BASE + VK_F5
	KEY_F6  KeyCode = EXTENDED_KEY_BASE + VK_F6
	KEY_F7  KeyCode = EXTENDED_KEY_BASE + VK_F7
	KEY_F8  KeyCode = EXTENDED_KEY_BASE + VK_F8
	KEY_F9  KeyCode = EXTENDED_KEY_BASE + VK_F9
	KEY_F10 KeyCode = EXTENDED_KEY_BASE + VK_F10
	KEY_F11 KeyCode = EXTENDED_KEY_BASE + VK_F11
	KEY_F12 KeyCode = EXTENDED_KEY_BASE + VK_F12

	KEY_F13 KeyCode = EXTENDED_KEY_BASE + VK_F13
	KEY_F14 KeyCode = EXTENDED_KEY_BASE + VK_F14
	KEY_F15 KeyCode = EXTENDED_KEY_BASE + VK_F15
	KEY_F16 KeyCode = EXTENDED_KEY_BASE + VK_F16
	KEY_F17 KeyCode = EXTENDED_KEY_BASE + VK_F17
	KEY_F18 KeyCode = EXTENDED_KEY_BASE + VK_F18
	KEY_F19 KeyCode = EXTENDED_KEY_BASE + VK_F19
	KEY_F20 KeyCode = EXTENDED_KEY_BASE + VK_F20
	KEY_F21 KeyCode = EXTENDED_KEY_BASE + VK_F21
	KEY_F22 KeyCode = EXTENDED_KEY_BASE + VK_F22
	KEY_F23 KeyCode = EXTENDED_KEY_BASE + VK_F23
	KEY_F24 KeyCode = EXTENDED_KEY_BASE + VK_F24

	KEY_NUMLOCK    KeyCode = EXTENDED_KEY_BASE + VK_NUMLOCK
	KEY_SCROLLLOCK KeyCode = EXTENDED_KEY_BASE + VK_SCROLL

	KEY_BROWSER_BACK        KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_BACK
	KEY_BROWSER_FORWARD     KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_FORWARD
	KEY_BROWSER_REFRESH     KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_REFRESH
	KEY_BROWSER_STOP        KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_STOP
	KEY_BROWSER_SEARCH      KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_SEARCH
	KEY_BROWSER_FAVORITES   KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_FAVORITES
	KEY_BROWSER_HOME        KeyCode = EXTENDED_KEY_BASE + VK_BROWSER_HOME
	KEY_VOLUME_MUTE         KeyCode = EXTENDED_KEY_BASE + VK_VOLUME_MUTE
	KEY_VOLUME_DOWN         KeyCode = EXTENDED_KEY_BASE + VK_VOLUME_DOWN
	KEY_VOLUME_UP           KeyCode = EXTENDED_KEY_BASE + VK_VOLUME_UP
	KEY_MEDIA_NEXT_TRACK    KeyCode = EXTENDED_KEY_BASE + VK_MEDIA_NEXT_TRACK
	KEY_MEDIA_PREV_TRACK    KeyCode = EXTENDED_KEY_BASE + VK_MEDIA_PREV_TRACK
	KEY_MEDIA_STOP          KeyCode = EXTENDED_KEY_BASE + VK_MEDIA_STOP
	KEY_MEDIA_PLAY_PAUSE    KeyCode = EXTENDED_KEY_BASE + VK_MEDIA_PLAY_PAUSE
	KEY_LAUNCH_MAIL         KeyCode = EXTENDED_KEY_BASE + VK_LAUNCH_MAIL
	KEY_LAUNCH_MEDIA_SELECT KeyCode = EXTENDED_KEY_BASE + VK_LAUNCH_MEDIA_SELECT
	KEY_LAUNCH_APP1         KeyCode = EXTENDED_KEY_BASE + VK_LAUNCH_APP1
	KEY_LAUNCH_APP2         KeyCode = EXTENDED_KEY_BASE + VK_LAUNCH_APP2

	KEY_CTRLALTSHIFTPRESS   KeyCode = INTERNAL_KEY_BASE + 1
	KEY_CTRLALTSHIFTRELEASE KeyCode = INTERNAL_KEY_BASE + 2

	KEY_MSWHEEL_UP   KeyCode = INTERNAL_KEY_BASE + 3
	KEY_MSWHEEL_DOWN KeyCode = INTERNAL_KEY_BASE + 4

	KEY_RCTRLALTSHIFTPRESS   KeyCode = INTERNAL_KEY_BASE + 7
	KEY_RCTRLALTSHIFTRELEASE KeyCode = INTERNAL_KEY_BASE + 8
	KEY_NUMDEL               KeyCode = INTERNAL_KEY_BASE + 9
	KEY_NUMENTER             KeyCode = INTERNAL_KEY_BASE + 0xB

	KEY_MSWHEEL_LEFT  KeyCode = INTERNAL_KEY_BASE + 0xC
	KEY_MSWHEEL_RIGHT KeyCode = INTERNAL_KEY_BASE + 0xD

	KEY_MSLCLICK KeyCode = INTERNAL_KEY_BASE + 0xF
	KEY_MSRCLICK KeyCode = INTERNAL_KEY_BASE + 0x10

	KEY_MSM1CLICK KeyCode = INTERNAL_KEY_BASE + 0x11
	KEY_MSM2CLICK KeyCode = INTERNAL_KEY_BASE + 0x12
	KEY_MSM3CLICK KeyCode = INTERNAL_KEY_BASE + 0x13

	KEY_MSLDBLCLICK KeyCode = INTERNAL_KEY_BASE + 0x14
	KEY_MSRDBLCLICK KeyCode = INTERNAL_KEY_BASE + 0x15

	KEY_MSM1DBLCLICK  KeyCode = INTERNAL_KEY_BASE + 0x16
	KEY_MSM2DBLCLICK  KeyCode = INTERNAL_KEY_BASE + 0x17
	KEY_MSM3DBLCLICK  KeyCode = INTERNAL_KEY_BASE + 0x18
	KEY_VK_0xFF_BEGIN KeyCode = EXTENDED_KEY_BASE + 0x00000100

	KEY_VK_0xFF_END KeyCode = EXTENDED_KEY_BASE + 0x000001FF

	KEY_END_FKEY KeyCode = 0x0001FFFF

	KEY_NONE     KeyCode = INTERNAL_KEY_BASE_2 + 1
	KEY_IDLE     KeyCode = INTERNAL_KEY_BASE_2 + 2
	KEY_DRAGCOPY KeyCode = INTERNAL_KEY_BASE_2 + 3
	KEY_DRAGMOVE KeyCode = INTERNAL_KEY_BASE_2 + 4

	KEY_KILLFOCUS                    KeyCode = INTERNAL_KEY_BASE_2 + 6
	KEY_GOTFOCUS                     KeyCode = INTERNAL_KEY_BASE_2 + 7
	KEY_CONSOLE_BUFFER_RESIZEKeyCode         = INTERNAL_KEY_BASE_2 + 8

	KEY_OP_BASE      KeyCode = INTERNAL_KEY_BASE_2 + 0x100
	KEY_OP_XLAT      KeyCode = KEY_OP_BASE + 0
	KEY_OP_PLAINTEXT KeyCode = KEY_OP_BASE + 2
	KEY_OP_SELWORD   KeyCode = KEY_OP_BASE + 3
	KEY_OP_ENDBASE   KeyCode = INTERNAL_KEY_BASE_2 + 0x1FF

	KEY_END_SKEY  KeyCode = 0x0003FFFF
	KEY_LAST_BASE KeyCode = KEY_END_SKEY

	KEY_MACRO_BASE    KeyCode = INTERNAL_MACRO_BASE
	KEY_MACRO_OP_BASE KeyCode = INTERNAL_MACRO_BASE + 0x0000
	KEY_MACRO_C_BASE  KeyCode = INTERNAL_MACRO_BASE + 0x0400
	KEY_MACRO_V_BASE  KeyCode = INTERNAL_MACRO_BASE + 0x0800
	KEY_MACRO_F_BASE  KeyCode = INTERNAL_MACRO_BASE + 0x0C00

	KEY_MACRO_U_BASE KeyCode = INTERNAL_MACRO_BASE + 0x8000

	KEY_MACRO_ENDBASE KeyCode = 0x000FFFFF

	KEY_CTRLSHIFT KeyCode = KEY_CTRL | KEY_SHIFT
	KEY_ALTSHIFT  KeyCode = KEY_ALT | KEY_SHIFT
	KEY_CTRLALT   KeyCode = KEY_CTRL | KEY_ALT

	KEY_CTRL0 KeyCode = KEY_CTRL + '0'
	KEY_CTRL1 KeyCode = KEY_CTRL + '1'
	KEY_CTRL2 KeyCode = KEY_CTRL + '2'
	KEY_CTRL3 KeyCode = KEY_CTRL + '3'
	KEY_CTRL4 KeyCode = KEY_CTRL + '4'
	KEY_CTRL5 KeyCode = KEY_CTRL + '5'
	KEY_CTRL6 KeyCode = KEY_CTRL + '6'
	KEY_CTRL7 KeyCode = KEY_CTRL + '7'
	KEY_CTRL8 KeyCode = KEY_CTRL + '8'
	KEY_CTRL9 KeyCode = KEY_CTRL + '9'

	KEY_RCTRL0 KeyCode = KEY_RCTRL + '0'
	KEY_RCTRL1 KeyCode = KEY_RCTRL + '1'
	KEY_RCTRL2 KeyCode = KEY_RCTRL + '2'
	KEY_RCTRL3 KeyCode = KEY_RCTRL + '3'
	KEY_RCTRL4 KeyCode = KEY_RCTRL + '4'
	KEY_RCTRL5 KeyCode = KEY_RCTRL + '5'
	KEY_RCTRL6 KeyCode = KEY_RCTRL + '6'
	KEY_RCTRL7 KeyCode = KEY_RCTRL + '7'
	KEY_RCTRL8 KeyCode = KEY_RCTRL + '8'
	KEY_RCTRL9 KeyCode = KEY_RCTRL + '9'

	KEY_CTRLA KeyCode = KEY_CTRL + 'A'
	KEY_CTRLB KeyCode = KEY_CTRL + 'B'
	KEY_CTRLC KeyCode = KEY_CTRL + 'C'
	KEY_CTRLD KeyCode = KEY_CTRL + 'D'
	KEY_CTRLE KeyCode = KEY_CTRL + 'E'
	KEY_CTRLF KeyCode = KEY_CTRL + 'F'
	KEY_CTRLG KeyCode = KEY_CTRL + 'G'
	KEY_CTRLH KeyCode = KEY_CTRL + 'H'
	KEY_CTRLI KeyCode = KEY_CTRL + 'I'
	KEY_CTRLJ KeyCode = KEY_CTRL + 'J'
	KEY_CTRLK KeyCode = KEY_CTRL + 'K'
	KEY_CTRLL KeyCode = KEY_CTRL + 'L'
	KEY_CTRLM KeyCode = KEY_CTRL + 'M'
	KEY_CTRLN KeyCode = KEY_CTRL + 'N'
	KEY_CTRLO KeyCode = KEY_CTRL + 'O'
	KEY_CTRLP KeyCode = KEY_CTRL + 'P'
	KEY_CTRLQ KeyCode = KEY_CTRL + 'Q'
	KEY_CTRLR KeyCode = KEY_CTRL + 'R'
	KEY_CTRLS KeyCode = KEY_CTRL + 'S'
	KEY_CTRLT KeyCode = KEY_CTRL + 'T'
	KEY_CTRLU KeyCode = KEY_CTRL + 'U'
	KEY_CTRLV KeyCode = KEY_CTRL + 'V'
	KEY_CTRLW KeyCode = KEY_CTRL + 'W'
	KEY_CTRLX KeyCode = KEY_CTRL + 'X'
	KEY_CTRLY KeyCode = KEY_CTRL + 'Y'
	KEY_CTRLZ KeyCode = KEY_CTRL + 'Z'

	KEY_CTRLBRACKET     KeyCode = KEY_CTRL | KEY_BRACKET
	KEY_CTRLBACKBRACKET KeyCode = KEY_CTRL | KEY_BACKBRACKET
	KEY_CTRLCOMMA       KeyCode = KEY_CTRL | KEY_COMMA
	KEY_CTRLQUOTE       KeyCode = KEY_CTRL | KEY_QUOTE
	KEY_CTRLDOT         KeyCode = KEY_CTRL | KEY_DOT

	KEY_ALT0 KeyCode = KEY_ALT + '0'
	KEY_ALT1 KeyCode = KEY_ALT + '1'
	KEY_ALT2 KeyCode = KEY_ALT + '2'
	KEY_ALT3 KeyCode = KEY_ALT + '3'
	KEY_ALT4 KeyCode = KEY_ALT + '4'
	KEY_ALT5 KeyCode = KEY_ALT + '5'
	KEY_ALT6 KeyCode = KEY_ALT + '6'
	KEY_ALT7 KeyCode = KEY_ALT + '7'
	KEY_ALT8 KeyCode = KEY_ALT + '8'
	KEY_ALT9 KeyCode = KEY_ALT + '9'

	KEY_ALTADD      KeyCode = KEY_ALT | KEY_ADD
	KEY_ALTDOT      KeyCode = KEY_ALT | KEY_DOT
	KEY_ALTCOMMA    KeyCode = KEY_ALT | KEY_COMMA
	KEY_ALTMULTIPLY KeyCode = KEY_ALT | KEY_MULTIPLY

	KEY_ALTA KeyCode = KEY_ALT + 'A'
	KEY_ALTB KeyCode = KEY_ALT + 'B'
	KEY_ALTC KeyCode = KEY_ALT + 'C'
	KEY_ALTD KeyCode = KEY_ALT + 'D'
	KEY_ALTE KeyCode = KEY_ALT + 'E'
	KEY_ALTF KeyCode = KEY_ALT + 'F'
	KEY_ALTG KeyCode = KEY_ALT + 'G'
	KEY_ALTH KeyCode = KEY_ALT + 'H'
	KEY_ALTI KeyCode = KEY_ALT + 'I'
	KEY_ALTJ KeyCode = KEY_ALT + 'J'
	KEY_ALTK KeyCode = KEY_ALT + 'K'
	KEY_ALTL KeyCode = KEY_ALT + 'L'
	KEY_ALTM KeyCode = KEY_ALT + 'M'
	KEY_ALTN KeyCode = KEY_ALT + 'N'
	KEY_ALTO KeyCode = KEY_ALT + 'O'
	KEY_ALTP KeyCode = KEY_ALT + 'P'
	KEY_ALTQ KeyCode = KEY_ALT + 'Q'
	KEY_ALTR KeyCode = KEY_ALT + 'R'
	KEY_ALTS KeyCode = KEY_ALT + 'S'
	KEY_ALTT KeyCode = KEY_ALT + 'T'
	KEY_ALTU KeyCode = KEY_ALT + 'U'
	KEY_ALTV KeyCode = KEY_ALT + 'V'
	KEY_ALTW KeyCode = KEY_ALT + 'W'
	KEY_ALTX KeyCode = KEY_ALT + 'X'
	KEY_ALTY KeyCode = KEY_ALT + 'Y'
	KEY_ALTZ KeyCode = KEY_ALT + 'Z'

	KEY_CTRLSHIFTADD      KeyCode = KEY_CTRL | KEY_SHIFT | KEY_ADD
	KEY_CTRLSHIFTSUBTRACT KeyCode = KEY_CTRL | KEY_SHIFT | KEY_SUBTRACT
	KEY_CTRLSHIFTDOT      KeyCode = KEY_CTRL | KEY_SHIFT | KEY_DOT
	KEY_CTRLSHIFTSLASH    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_SLASH

	KEY_CTRLSHIFT0 KeyCode = (KEY_CTRL | KEY_SHIFT) + '0'
	KEY_CTRLSHIFT1 KeyCode = (KEY_CTRL | KEY_SHIFT) + '1'
	KEY_CTRLSHIFT2 KeyCode = (KEY_CTRL | KEY_SHIFT) + '2'
	KEY_CTRLSHIFT3 KeyCode = (KEY_CTRL | KEY_SHIFT) + '3'
	KEY_CTRLSHIFT4 KeyCode = (KEY_CTRL | KEY_SHIFT) + '4'
	KEY_CTRLSHIFT5 KeyCode = (KEY_CTRL | KEY_SHIFT) + '5'
	KEY_CTRLSHIFT6 KeyCode = (KEY_CTRL | KEY_SHIFT) + '6'
	KEY_CTRLSHIFT7 KeyCode = (KEY_CTRL | KEY_SHIFT) + '7'
	KEY_CTRLSHIFT8 KeyCode = (KEY_CTRL | KEY_SHIFT) + '8'
	KEY_CTRLSHIFT9 KeyCode = (KEY_CTRL | KEY_SHIFT) + '9'

	KEY_RCTRLSHIFT0 KeyCode = KEY_RCTRL + KEY_SHIFT + '0'
	KEY_RCTRLSHIFT1 KeyCode = KEY_RCTRL + KEY_SHIFT + '1'
	KEY_RCTRLSHIFT2 KeyCode = KEY_RCTRL + KEY_SHIFT + '2'
	KEY_RCTRLSHIFT3 KeyCode = KEY_RCTRL + KEY_SHIFT + '3'
	KEY_RCTRLSHIFT4 KeyCode = KEY_RCTRL + KEY_SHIFT + '4'
	KEY_RCTRLSHIFT5 KeyCode = KEY_RCTRL + KEY_SHIFT + '5'
	KEY_RCTRLSHIFT6 KeyCode = KEY_RCTRL + KEY_SHIFT + '6'
	KEY_RCTRLSHIFT7 KeyCode = KEY_RCTRL + KEY_SHIFT + '7'
	KEY_RCTRLSHIFT8 KeyCode = KEY_RCTRL + KEY_SHIFT + '8'
	KEY_RCTRLSHIFT9 KeyCode = KEY_RCTRL + KEY_SHIFT + '9'

	KEY_CTRLSHIFTA KeyCode = (KEY_CTRL | KEY_SHIFT) + 'A'
	KEY_CTRLSHIFTB KeyCode = (KEY_CTRL | KEY_SHIFT) + 'B'
	KEY_CTRLSHIFTC KeyCode = (KEY_CTRL | KEY_SHIFT) + 'C'
	KEY_CTRLSHIFTD KeyCode = (KEY_CTRL | KEY_SHIFT) + 'D'
	KEY_CTRLSHIFTE KeyCode = (KEY_CTRL | KEY_SHIFT) + 'E'
	KEY_CTRLSHIFTF KeyCode = (KEY_CTRL | KEY_SHIFT) + 'F'
	KEY_CTRLSHIFTG KeyCode = (KEY_CTRL | KEY_SHIFT) + 'G'
	KEY_CTRLSHIFTH KeyCode = (KEY_CTRL | KEY_SHIFT) + 'H'
	KEY_CTRLSHIFTI KeyCode = (KEY_CTRL | KEY_SHIFT) + 'I'
	KEY_CTRLSHIFTJ KeyCode = (KEY_CTRL | KEY_SHIFT) + 'J'
	KEY_CTRLSHIFTK KeyCode = (KEY_CTRL | KEY_SHIFT) + 'K'
	KEY_CTRLSHIFTL KeyCode = (KEY_CTRL | KEY_SHIFT) + 'L'
	KEY_CTRLSHIFTM KeyCode = (KEY_CTRL | KEY_SHIFT) + 'M'
	KEY_CTRLSHIFTN KeyCode = (KEY_CTRL | KEY_SHIFT) + 'N'
	KEY_CTRLSHIFTO KeyCode = (KEY_CTRL | KEY_SHIFT) + 'O'
	KEY_CTRLSHIFTP KeyCode = (KEY_CTRL | KEY_SHIFT) + 'P'
	KEY_CTRLSHIFTQ KeyCode = (KEY_CTRL | KEY_SHIFT) + 'Q'
	KEY_CTRLSHIFTR KeyCode = (KEY_CTRL | KEY_SHIFT) + 'R'
	KEY_CTRLSHIFTS KeyCode = (KEY_CTRL | KEY_SHIFT) + 'S'
	KEY_CTRLSHIFTT KeyCode = (KEY_CTRL | KEY_SHIFT) + 'T'
	KEY_CTRLSHIFTU KeyCode = (KEY_CTRL | KEY_SHIFT) + 'U'
	KEY_CTRLSHIFTV KeyCode = (KEY_CTRL | KEY_SHIFT) + 'V'
	KEY_CTRLSHIFTW KeyCode = (KEY_CTRL | KEY_SHIFT) + 'W'
	KEY_CTRLSHIFTX KeyCode = (KEY_CTRL | KEY_SHIFT) + 'X'
	KEY_CTRLSHIFTY KeyCode = (KEY_CTRL | KEY_SHIFT) + 'Y'
	KEY_CTRLSHIFTZ KeyCode = (KEY_CTRL | KEY_SHIFT) + 'Z'

	KEY_CTRLSHIFTBRACKET     KeyCode = KEY_CTRL | KEY_SHIFT | KEY_BRACKET
	KEY_CTRLSHIFTBACKSLASH   KeyCode = KEY_CTRL | KEY_SHIFT | KEY_BACKSLASH
	KEY_CTRLSHIFTBACKBRACKET KeyCode = KEY_CTRL | KEY_SHIFT | KEY_BACKBRACKET

	KEY_ALTSHIFT0 KeyCode = (KEY_ALT | KEY_SHIFT) + '0'
	KEY_ALTSHIFT1 KeyCode = (KEY_ALT | KEY_SHIFT) + '1'
	KEY_ALTSHIFT2 KeyCode = (KEY_ALT | KEY_SHIFT) + '2'
	KEY_ALTSHIFT3 KeyCode = (KEY_ALT | KEY_SHIFT) + '3'
	KEY_ALTSHIFT4 KeyCode = (KEY_ALT | KEY_SHIFT) + '4'
	KEY_ALTSHIFT5 KeyCode = (KEY_ALT | KEY_SHIFT) + '5'
	KEY_ALTSHIFT6 KeyCode = (KEY_ALT | KEY_SHIFT) + '6'
	KEY_ALTSHIFT7 KeyCode = (KEY_ALT | KEY_SHIFT) + '7'
	KEY_ALTSHIFT8 KeyCode = (KEY_ALT | KEY_SHIFT) + '8'
	KEY_ALTSHIFT9 KeyCode = (KEY_ALT | KEY_SHIFT) + '9'

	KEY_ALTSHIFTA KeyCode = (KEY_ALT | KEY_SHIFT) + 'A'
	KEY_ALTSHIFTB KeyCode = (KEY_ALT | KEY_SHIFT) + 'B'
	KEY_ALTSHIFTC KeyCode = (KEY_ALT | KEY_SHIFT) + 'C'
	KEY_ALTSHIFTD KeyCode = (KEY_ALT | KEY_SHIFT) + 'D'
	KEY_ALTSHIFTE KeyCode = (KEY_ALT | KEY_SHIFT) + 'E'
	KEY_ALTSHIFTF KeyCode = (KEY_ALT | KEY_SHIFT) + 'F'
	KEY_ALTSHIFTG KeyCode = (KEY_ALT | KEY_SHIFT) + 'G'
	KEY_ALTSHIFTH KeyCode = (KEY_ALT | KEY_SHIFT) + 'H'
	KEY_ALTSHIFTI KeyCode = (KEY_ALT | KEY_SHIFT) + 'I'
	KEY_ALTSHIFTJ KeyCode = (KEY_ALT | KEY_SHIFT) + 'J'
	KEY_ALTSHIFTK KeyCode = (KEY_ALT | KEY_SHIFT) + 'K'
	KEY_ALTSHIFTL KeyCode = (KEY_ALT | KEY_SHIFT) + 'L'
	KEY_ALTSHIFTM KeyCode = (KEY_ALT | KEY_SHIFT) + 'M'
	KEY_ALTSHIFTN KeyCode = (KEY_ALT | KEY_SHIFT) + 'N'
	KEY_ALTSHIFTO KeyCode = (KEY_ALT | KEY_SHIFT) + 'O'
	KEY_ALTSHIFTP KeyCode = (KEY_ALT | KEY_SHIFT) + 'P'
	KEY_ALTSHIFTQ KeyCode = (KEY_ALT | KEY_SHIFT) + 'Q'
	KEY_ALTSHIFTR KeyCode = (KEY_ALT | KEY_SHIFT) + 'R'
	KEY_ALTSHIFTS KeyCode = (KEY_ALT | KEY_SHIFT) + 'S'
	KEY_ALTSHIFTT KeyCode = (KEY_ALT | KEY_SHIFT) + 'T'
	KEY_ALTSHIFTU KeyCode = (KEY_ALT | KEY_SHIFT) + 'U'
	KEY_ALTSHIFTV KeyCode = (KEY_ALT | KEY_SHIFT) + 'V'
	KEY_ALTSHIFTW KeyCode = (KEY_ALT | KEY_SHIFT) + 'W'
	KEY_ALTSHIFTX KeyCode = (KEY_ALT | KEY_SHIFT) + 'X'
	KEY_ALTSHIFTY KeyCode = (KEY_ALT | KEY_SHIFT) + 'Y'
	KEY_ALTSHIFTZ KeyCode = (KEY_ALT | KEY_SHIFT) + 'Z'

	KEY_ALTSHIFTBRACKET     KeyCode = KEY_ALT | KEY_SHIFT | KEY_BRACKET
	KEY_ALTSHIFTBACKBRACKET KeyCode = KEY_ALT | KEY_SHIFT | KEY_BACKBRACKET

	KEY_CTRLALT0 KeyCode = (KEY_CTRL | KEY_ALT) + '0'
	KEY_CTRLALT1 KeyCode = (KEY_CTRL | KEY_ALT) + '1'
	KEY_CTRLALT2 KeyCode = (KEY_CTRL | KEY_ALT) + '2'
	KEY_CTRLALT3 KeyCode = (KEY_CTRL | KEY_ALT) + '3'
	KEY_CTRLALT4 KeyCode = (KEY_CTRL | KEY_ALT) + '4'
	KEY_CTRLALT5 KeyCode = (KEY_CTRL | KEY_ALT) + '5'
	KEY_CTRLALT6 KeyCode = (KEY_CTRL | KEY_ALT) + '6'
	KEY_CTRLALT7 KeyCode = (KEY_CTRL | KEY_ALT) + '7'
	KEY_CTRLALT8 KeyCode = (KEY_CTRL | KEY_ALT) + '8'
	KEY_CTRLALT9 KeyCode = (KEY_CTRL | KEY_ALT) + '9'

	KEY_CTRLALTA KeyCode = (KEY_CTRL | KEY_ALT) + 'A'
	KEY_CTRLALTB KeyCode = (KEY_CTRL | KEY_ALT) + 'B'
	KEY_CTRLALTC KeyCode = (KEY_CTRL | KEY_ALT) + 'C'
	KEY_CTRLALTD KeyCode = (KEY_CTRL | KEY_ALT) + 'D'
	KEY_CTRLALTE KeyCode = (KEY_CTRL | KEY_ALT) + 'E'
	KEY_CTRLALTF KeyCode = (KEY_CTRL | KEY_ALT) + 'F'
	KEY_CTRLALTG KeyCode = (KEY_CTRL | KEY_ALT) + 'G'
	KEY_CTRLALTH KeyCode = (KEY_CTRL | KEY_ALT) + 'H'
	KEY_CTRLALTI KeyCode = (KEY_CTRL | KEY_ALT) + 'I'
	KEY_CTRLALTJ KeyCode = (KEY_CTRL | KEY_ALT) + 'J'
	KEY_CTRLALTK KeyCode = (KEY_CTRL | KEY_ALT) + 'K'
	KEY_CTRLALTL KeyCode = (KEY_CTRL | KEY_ALT) + 'L'
	KEY_CTRLALTM KeyCode = (KEY_CTRL | KEY_ALT) + 'M'
	KEY_CTRLALTN KeyCode = (KEY_CTRL | KEY_ALT) + 'N'
	KEY_CTRLALTO KeyCode = (KEY_CTRL | KEY_ALT) + 'O'
	KEY_CTRLALTP KeyCode = (KEY_CTRL | KEY_ALT) + 'P'
	KEY_CTRLALTQ KeyCode = (KEY_CTRL | KEY_ALT) + 'Q'
	KEY_CTRLALTR KeyCode = (KEY_CTRL | KEY_ALT) + 'R'
	KEY_CTRLALTS KeyCode = (KEY_CTRL | KEY_ALT) + 'S'
	KEY_CTRLALTT KeyCode = (KEY_CTRL | KEY_ALT) + 'T'
	KEY_CTRLALTU KeyCode = (KEY_CTRL | KEY_ALT) + 'U'
	KEY_CTRLALTV KeyCode = (KEY_CTRL | KEY_ALT) + 'V'
	KEY_CTRLALTW KeyCode = (KEY_CTRL | KEY_ALT) + 'W'
	KEY_CTRLALTX KeyCode = (KEY_CTRL | KEY_ALT) + 'X'
	KEY_CTRLALTY KeyCode = (KEY_CTRL | KEY_ALT) + 'Y'
	KEY_CTRLALTZ KeyCode = (KEY_CTRL | KEY_ALT) + 'Z'

	KEY_CTRLALTBRACKET     KeyCode = KEY_CTRL | KEY_ALT | KEY_BRACKET
	KEY_CTRLALTBACKBRACKET KeyCode = KEY_CTRL | KEY_ALT | KEY_BACKBRACKET

	KEY_CTRLF1  KeyCode = KEY_CTRL | KEY_F1
	KEY_CTRLF2  KeyCode = KEY_CTRL | KEY_F2
	KEY_CTRLF3  KeyCode = KEY_CTRL | KEY_F3
	KEY_CTRLF4  KeyCode = KEY_CTRL | KEY_F4
	KEY_CTRLF5  KeyCode = KEY_CTRL | KEY_F5
	KEY_CTRLF6  KeyCode = KEY_CTRL | KEY_F6
	KEY_CTRLF7  KeyCode = KEY_CTRL | KEY_F7
	KEY_CTRLF8  KeyCode = KEY_CTRL | KEY_F8
	KEY_CTRLF9  KeyCode = KEY_CTRL | KEY_F9
	KEY_CTRLF10 KeyCode = KEY_CTRL | KEY_F10
	KEY_CTRLF11 KeyCode = KEY_CTRL | KEY_F11
	KEY_CTRLF12 KeyCode = KEY_CTRL | KEY_F12

	KEY_SHIFTF1  KeyCode = KEY_SHIFT | KEY_F1
	KEY_SHIFTF2  KeyCode = KEY_SHIFT | KEY_F2
	KEY_SHIFTF3  KeyCode = KEY_SHIFT | KEY_F3
	KEY_SHIFTF4  KeyCode = KEY_SHIFT | KEY_F4
	KEY_SHIFTF5  KeyCode = KEY_SHIFT | KEY_F5
	KEY_SHIFTF6  KeyCode = KEY_SHIFT | KEY_F6
	KEY_SHIFTF7  KeyCode = KEY_SHIFT | KEY_F7
	KEY_SHIFTF8  KeyCode = KEY_SHIFT | KEY_F8
	KEY_SHIFTF9  KeyCode = KEY_SHIFT | KEY_F9
	KEY_SHIFTF10 KeyCode = KEY_SHIFT | KEY_F10
	KEY_SHIFTF11 KeyCode = KEY_SHIFT | KEY_F11
	KEY_SHIFTF12 KeyCode = KEY_SHIFT | KEY_F12

	KEY_ALTF1  KeyCode = KEY_ALT | KEY_F1
	KEY_ALTF2  KeyCode = KEY_ALT | KEY_F2
	KEY_ALTF3  KeyCode = KEY_ALT | KEY_F3
	KEY_ALTF4  KeyCode = KEY_ALT | KEY_F4
	KEY_ALTF5  KeyCode = KEY_ALT | KEY_F5
	KEY_ALTF6  KeyCode = KEY_ALT | KEY_F6
	KEY_ALTF7  KeyCode = KEY_ALT | KEY_F7
	KEY_ALTF8  KeyCode = KEY_ALT | KEY_F8
	KEY_ALTF9  KeyCode = KEY_ALT | KEY_F9
	KEY_ALTF10 KeyCode = KEY_ALT | KEY_F10
	KEY_ALTF11 KeyCode = KEY_ALT | KEY_F11
	KEY_ALTF12 KeyCode = KEY_ALT | KEY_F12

	KEY_CTRLSHIFTF1  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F1
	KEY_CTRLSHIFTF2  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F2
	KEY_CTRLSHIFTF3  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F3
	KEY_CTRLSHIFTF4  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F4
	KEY_CTRLSHIFTF5  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F5
	KEY_CTRLSHIFTF6  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F6
	KEY_CTRLSHIFTF7  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F7
	KEY_CTRLSHIFTF8  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F8
	KEY_CTRLSHIFTF9  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F9
	KEY_CTRLSHIFTF10 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F10
	KEY_CTRLSHIFTF11 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F11
	KEY_CTRLSHIFTF12 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_F12

	KEY_ALTSHIFTF1  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F1
	KEY_ALTSHIFTF2  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F2
	KEY_ALTSHIFTF3  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F3
	KEY_ALTSHIFTF4  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F4
	KEY_ALTSHIFTF5  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F5
	KEY_ALTSHIFTF6  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F6
	KEY_ALTSHIFTF7  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F7
	KEY_ALTSHIFTF8  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F8
	KEY_ALTSHIFTF9  KeyCode = KEY_ALT | KEY_SHIFT | KEY_F9
	KEY_ALTSHIFTF10 KeyCode = KEY_ALT | KEY_SHIFT | KEY_F10
	KEY_ALTSHIFTF11 KeyCode = KEY_ALT | KEY_SHIFT | KEY_F11
	KEY_ALTSHIFTF12 KeyCode = KEY_ALT | KEY_SHIFT | KEY_F12

	KEY_CTRLALTF1  KeyCode = KEY_CTRL | KEY_ALT | KEY_F1
	KEY_CTRLALTF2  KeyCode = KEY_CTRL | KEY_ALT | KEY_F2
	KEY_CTRLALTF3  KeyCode = KEY_CTRL | KEY_ALT | KEY_F3
	KEY_CTRLALTF4  KeyCode = KEY_CTRL | KEY_ALT | KEY_F4
	KEY_CTRLALTF5  KeyCode = KEY_CTRL | KEY_ALT | KEY_F5
	KEY_CTRLALTF6  KeyCode = KEY_CTRL | KEY_ALT | KEY_F6
	KEY_CTRLALTF7  KeyCode = KEY_CTRL | KEY_ALT | KEY_F7
	KEY_CTRLALTF8  KeyCode = KEY_CTRL | KEY_ALT | KEY_F8
	KEY_CTRLALTF9  KeyCode = KEY_CTRL | KEY_ALT | KEY_F9
	KEY_CTRLALTF10 KeyCode = KEY_CTRL | KEY_ALT | KEY_F10
	KEY_CTRLALTF11 KeyCode = KEY_CTRL | KEY_ALT | KEY_F11
	KEY_CTRLALTF12 KeyCode = KEY_CTRL | KEY_ALT | KEY_F12

	KEY_CTRLHOME    KeyCode = KEY_CTRL | KEY_HOME
	KEY_CTRLUP      KeyCode = KEY_CTRL | KEY_UP
	KEY_CTRLPGUP    KeyCode = KEY_CTRL | KEY_PGUP
	KEY_CTRLLEFT    KeyCode = KEY_CTRL | KEY_LEFT
	KEY_CTRLRIGHT   KeyCode = KEY_CTRL | KEY_RIGHT
	KEY_CTRLEND     KeyCode = KEY_CTRL | KEY_END
	KEY_CTRLDOWN    KeyCode = KEY_CTRL | KEY_DOWN
	KEY_CTRLPGDN    KeyCode = KEY_CTRL | KEY_PGDN
	KEY_CTRLINS     KeyCode = KEY_CTRL | KEY_INS
	KEY_CTRLDEL     KeyCode = KEY_CTRL | KEY_DEL
	KEY_CTRLNUMDEL  KeyCode = KEY_CTRL | KEY_NUMDEL
	KEY_CTRLDECIMAL KeyCode = KEY_CTRL | KEY_DECIMAL

	KEY_SHIFTHOME    KeyCode = KEY_SHIFT | KEY_HOME
	KEY_SHIFTUP      KeyCode = KEY_SHIFT | KEY_UP
	KEY_SHIFTPGUP    KeyCode = KEY_SHIFT | KEY_PGUP
	KEY_SHIFTLEFT    KeyCode = KEY_SHIFT | KEY_LEFT
	KEY_SHIFTRIGHT   KeyCode = KEY_SHIFT | KEY_RIGHT
	KEY_SHIFTEND     KeyCode = KEY_SHIFT | KEY_END
	KEY_SHIFTDOWN    KeyCode = KEY_SHIFT | KEY_DOWN
	KEY_SHIFTPGDN    KeyCode = KEY_SHIFT | KEY_PGDN
	KEY_SHIFTINS     KeyCode = KEY_SHIFT | KEY_INS
	KEY_SHIFTDEL     KeyCode = KEY_SHIFT | KEY_DEL
	KEY_SHIFTNUMDEL  KeyCode = KEY_SHIFT | KEY_NUMDEL
	KEY_SHIFTDECIMAL KeyCode = KEY_SHIFT | KEY_DECIMAL

	KEY_ALTHOME    KeyCode = KEY_ALT | KEY_HOME
	KEY_ALTUP      KeyCode = KEY_ALT | KEY_UP
	KEY_ALTPGUP    KeyCode = KEY_ALT | KEY_PGUP
	KEY_ALTLEFT    KeyCode = KEY_ALT | KEY_LEFT
	KEY_ALTRIGHT   KeyCode = KEY_ALT | KEY_RIGHT
	KEY_ALTEND     KeyCode = KEY_ALT | KEY_END
	KEY_ALTDOWN    KeyCode = KEY_ALT | KEY_DOWN
	KEY_ALTPGDN    KeyCode = KEY_ALT | KEY_PGDN
	KEY_ALTINS     KeyCode = KEY_ALT | KEY_INS
	KEY_ALTDEL     KeyCode = KEY_ALT | KEY_DEL
	KEY_ALTNUMDEL  KeyCode = KEY_ALT | KEY_NUMDEL
	KEY_ALTDECIMAL KeyCode = KEY_ALT | KEY_DECIMAL

	KEY_CTRLSHIFTHOME    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_HOME
	KEY_CTRLSHIFTUP      KeyCode = KEY_CTRL | KEY_SHIFT | KEY_UP
	KEY_CTRLSHIFTPGUP    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_PGUP
	KEY_CTRLSHIFTLEFT    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_LEFT
	KEY_CTRLSHIFTRIGHT   KeyCode = KEY_CTRL | KEY_SHIFT | KEY_RIGHT
	KEY_CTRLSHIFTEND     KeyCode = KEY_CTRL | KEY_SHIFT | KEY_END
	KEY_CTRLSHIFTDOWN    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_DOWN
	KEY_CTRLSHIFTPGDN    KeyCode = KEY_CTRL | KEY_SHIFT | KEY_PGDN
	KEY_CTRLSHIFTINS     KeyCode = KEY_CTRL | KEY_SHIFT | KEY_INS
	KEY_CTRLSHIFTDEL     KeyCode = KEY_CTRL | KEY_SHIFT | KEY_DEL
	KEY_CTRLSHIFTNUMDEL  KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMDEL
	KEY_CTRLSHIFTDECIMAL KeyCode = KEY_CTRL | KEY_SHIFT | KEY_DECIMAL

	KEY_ALTSHIFTHOME    KeyCode = KEY_ALT | KEY_SHIFT | KEY_HOME
	KEY_ALTSHIFTUP      KeyCode = KEY_ALT | KEY_SHIFT | KEY_UP
	KEY_ALTSHIFTPGUP    KeyCode = KEY_ALT | KEY_SHIFT | KEY_PGUP
	KEY_ALTSHIFTLEFT    KeyCode = KEY_ALT | KEY_SHIFT | KEY_LEFT
	KEY_ALTSHIFTRIGHT   KeyCode = KEY_ALT | KEY_SHIFT | KEY_RIGHT
	KEY_ALTSHIFTEND     KeyCode = KEY_ALT | KEY_SHIFT | KEY_END
	KEY_ALTSHIFTDOWN    KeyCode = KEY_ALT | KEY_SHIFT | KEY_DOWN
	KEY_ALTSHIFTPGDN    KeyCode = KEY_ALT | KEY_SHIFT | KEY_PGDN
	KEY_ALTSHIFTINS     KeyCode = KEY_ALT | KEY_SHIFT | KEY_INS
	KEY_ALTSHIFTDEL     KeyCode = KEY_ALT | KEY_SHIFT | KEY_DEL
	KEY_ALTSHIFTNUMDEL  KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMDEL
	KEY_ALTSHIFTDECIMAL KeyCode = KEY_ALT | KEY_SHIFT | KEY_DECIMAL

	KEY_CTRLALTHOME  KeyCode = KEY_CTRL | KEY_ALT | KEY_HOME
	KEY_CTRLALTUP    KeyCode = KEY_CTRL | KEY_ALT | KEY_UP
	KEY_CTRLALTPGUP  KeyCode = KEY_CTRL | KEY_ALT | KEY_PGUP
	KEY_CTRLALTLEFT  KeyCode = KEY_CTRL | KEY_ALT | KEY_LEFT
	KEY_CTRLALTRIGHT KeyCode = KEY_CTRL | KEY_ALT | KEY_RIGHT
	KEY_CTRLALTEND   KeyCode = KEY_CTRL | KEY_ALT | KEY_END
	KEY_CTRLALTDOWN  KeyCode = KEY_CTRL | KEY_ALT | KEY_DOWN
	KEY_CTRLALTPGDN  KeyCode = KEY_CTRL | KEY_ALT | KEY_PGDN
	KEY_CTRLALTINS   KeyCode = KEY_CTRL | KEY_ALT | KEY_INS

	KEY_CTRLNUMPAD0 KeyCode = KEY_CTRL | KEY_NUMPAD0
	KEY_CTRLNUMPAD1 KeyCode = KEY_CTRL | KEY_NUMPAD1
	KEY_CTRLNUMPAD2 KeyCode = KEY_CTRL | KEY_NUMPAD2
	KEY_CTRLNUMPAD3 KeyCode = KEY_CTRL | KEY_NUMPAD3
	KEY_CTRLNUMPAD4 KeyCode = KEY_CTRL | KEY_NUMPAD4
	KEY_CTRLNUMPAD5 KeyCode = KEY_CTRL | KEY_NUMPAD5
	KEY_CTRLNUMPAD6 KeyCode = KEY_CTRL | KEY_NUMPAD6
	KEY_CTRLNUMPAD7 KeyCode = KEY_CTRL | KEY_NUMPAD7
	KEY_CTRLNUMPAD8 KeyCode = KEY_CTRL | KEY_NUMPAD8
	KEY_CTRLNUMPAD9 KeyCode = KEY_CTRL | KEY_NUMPAD9

	KEY_SHIFTNUMPAD0 KeyCode = KEY_SHIFT | KEY_NUMPAD0
	KEY_SHIFTNUMPAD1 KeyCode = KEY_SHIFT | KEY_NUMPAD1
	KEY_SHIFTNUMPAD2 KeyCode = KEY_SHIFT | KEY_NUMPAD2
	KEY_SHIFTNUMPAD3 KeyCode = KEY_SHIFT | KEY_NUMPAD3
	KEY_SHIFTNUMPAD4 KeyCode = KEY_SHIFT | KEY_NUMPAD4
	KEY_SHIFTNUMPAD5 KeyCode = KEY_SHIFT | KEY_NUMPAD5
	KEY_SHIFTNUMPAD6 KeyCode = KEY_SHIFT | KEY_NUMPAD6
	KEY_SHIFTNUMPAD7 KeyCode = KEY_SHIFT | KEY_NUMPAD7
	KEY_SHIFTNUMPAD8 KeyCode = KEY_SHIFT | KEY_NUMPAD8
	KEY_SHIFTNUMPAD9 KeyCode = KEY_SHIFT | KEY_NUMPAD9

	KEY_CTRLSHIFTNUMPAD0 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD0
	KEY_CTRLSHIFTNUMPAD1 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD1
	KEY_CTRLSHIFTNUMPAD2 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD2
	KEY_CTRLSHIFTNUMPAD3 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD3
	KEY_CTRLSHIFTNUMPAD4 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD4
	KEY_CTRLSHIFTNUMPAD5 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD5
	KEY_CTRLSHIFTNUMPAD6 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD6
	KEY_CTRLSHIFTNUMPAD7 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD7
	KEY_CTRLSHIFTNUMPAD8 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD8
	KEY_CTRLSHIFTNUMPAD9 KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMPAD9

	KEY_CTRLALTNUMPAD0 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD0
	KEY_CTRLALTNUMPAD1 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD1
	KEY_CTRLALTNUMPAD2 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD2
	KEY_CTRLALTNUMPAD3 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD3
	KEY_CTRLALTNUMPAD4 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD4
	KEY_CTRLALTNUMPAD5 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD5
	KEY_CTRLALTNUMPAD6 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD6
	KEY_CTRLALTNUMPAD7 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD7
	KEY_CTRLALTNUMPAD8 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD8
	KEY_CTRLALTNUMPAD9 KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMPAD9

	KEY_ALTSHIFTNUMPAD0 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD0
	KEY_ALTSHIFTNUMPAD1 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD1
	KEY_ALTSHIFTNUMPAD2 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD2
	KEY_ALTSHIFTNUMPAD3 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD3
	KEY_ALTSHIFTNUMPAD4 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD4
	KEY_ALTSHIFTNUMPAD5 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD5
	KEY_ALTSHIFTNUMPAD6 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD6
	KEY_ALTSHIFTNUMPAD7 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD7
	KEY_ALTSHIFTNUMPAD8 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD8
	KEY_ALTSHIFTNUMPAD9 KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMPAD9

	KEY_CTRLSLASH      KeyCode = KEY_CTRL | KEY_SLASH
	KEY_CTRLBACKSLASH  KeyCode = KEY_CTRL | KEY_BACKSLASH
	KEY_CTRLCLEAR      KeyCode = KEY_CTRL | KEY_CLEAR
	KEY_CTRLSHIFTCLEAR KeyCode = KEY_CTRL | KEY_SHIFT | KEY_CLEAR
	KEY_CTRLALTCLEAR   KeyCode = KEY_CTRL | KEY_ALT | KEY_CLEAR
	KEY_CTRLADD        KeyCode = KEY_CTRL | KEY_ADD
	KEY_SHIFTADD       KeyCode = KEY_SHIFT | KEY_ADD

	KEY_CTRLSUBTRACT  KeyCode = KEY_CTRL | KEY_SUBTRACT
	KEY_ALTSUBTRACT   KeyCode = KEY_ALT | KEY_SUBTRACT
	KEY_SHIFTSUBTRACT KeyCode = KEY_SHIFT | KEY_SUBTRACT
	KEY_CTRLMULTIPLY  KeyCode = KEY_CTRL | KEY_MULTIPLY

	KEY_CTRLBS      KeyCode = KEY_CTRL | KEY_BS
	KEY_ALTBS       KeyCode = KEY_ALT | KEY_BS
	KEY_CTRLSHIFTBS KeyCode = KEY_CTRL | KEY_SHIFT | KEY_BS
	KEY_SHIFTBS     KeyCode = KEY_SHIFT | KEY_BS

	KEY_CTRLSHIFTTAB KeyCode = KEY_CTRL | KEY_SHIFT | KEY_TAB
	KEY_CTRLTAB      KeyCode = KEY_CTRL | KEY_TAB
	KEY_SHIFTTAB     KeyCode = KEY_SHIFT | KEY_TAB

	KEY_CTRLENTER      KeyCode = KEY_CTRL | KEY_ENTER
	KEY_SHIFTENTER     KeyCode = KEY_SHIFT | KEY_ENTER
	KEY_ALTSHIFTENTER  KeyCode = KEY_ALT | KEY_SHIFT | KEY_ENTER
	KEY_CTRLALTENTER   KeyCode = KEY_CTRL | KEY_ALT | KEY_ENTER
	KEY_CTRLSHIFTENTER KeyCode = KEY_CTRL | KEY_SHIFT | KEY_ENTER

	KEY_CTRLNUMENTER      KeyCode = KEY_CTRL | KEY_NUMENTER
	KEY_SHIFTNUMENTER     KeyCode = KEY_SHIFT | KEY_NUMENTER
	KEY_ALTSHIFTNUMENTER  KeyCode = KEY_ALT | KEY_SHIFT | KEY_NUMENTER
	KEY_CTRLALTNUMENTER   KeyCode = KEY_CTRL | KEY_ALT | KEY_NUMENTER
	KEY_CTRLSHIFTNUMENTER KeyCode = KEY_CTRL | KEY_SHIFT | KEY_NUMENTER

	KEY_CTRLAPPS      KeyCode = KEY_CTRL | KEY_APPS
	KEY_ALTAPPS       KeyCode = KEY_ALT | KEY_APPS
	KEY_SHIFTAPPS     KeyCode = KEY_SHIFT | KEY_APPS
	KEY_CTRLSHIFTAPPS KeyCode = KEY_CTRL | KEY_SHIFT | KEY_APPS
	KEY_ALTSHIFTAPPS  KeyCode = KEY_ALT | KEY_SHIFT | KEY_APPS
	KEY_CTRLALTAPPS   KeyCode = KEY_CTRL | KEY_ALT | KEY_APPS

	KEY_CTRLSPACE      KeyCode = KEY_CTRL | KEY_SPACE
	KEY_SHIFTSPACE     KeyCode = KEY_SHIFT | KEY_SPACE
	KEY_CTRLSHIFTSPACE KeyCode = KEY_CTRL | KEY_SHIFT | KEY_SPACE

	KEY_ALT_BASE      KeyCode = KEY_ALT
	KEY_ALTSHIFT_BASE KeyCode = KEY_ALTSHIFT
)
